### ISSUE TITLE
External 4k monitor blanks out periodically

### ISSUE THREAD

**Issue by cboettig** [advancingu/XPS13Linux#20]
Most of the time I have my XPS 13 (dev edition) connected to an external 4k Dell monitor over mini-displayport.  Periodically the external display goes blank; usually when launching an application.  This usually seems to happen more soon after the system has been rebooted.  Sometimes the display returns by itself, other times I must do something like close and re-open the laptop lid to bring the display back.  Not sure how to debug or what is causing the issue.  As best as I can tell it is not a loose cable or physical movement of the devices that cause this.

**Comment by soren121** [comment]
Sounds like a GPU driver issue. Do you see anything of interest in dmesg?

**Comment by cboettig** [comment]
Not sure, but these lines from `dmesg` look possibly related(?):

```
perf interrupt took too long (5017 > 5000), lowering kernel.perf_event_max_sample_rate to 25000
[130856.879081] i915 0000:00:02.0: BAR 6: [??? 0x00000000 flags 0x2] has bogus alignment
[130864.161375] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun
```

**Comment by advancingu** [comment]
@cboettig Maybe try upgrading your drivers with those from the [oibaf PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) and see if that helps.

**Comment by cboettig** [comment]
hmm, upgrading the drivers went particularly poorly.  Couldn't successfully reboot the machine, even in safe mode.  Did a fresh Ubuntu 15.04 install from usb. (everything backed up so no data loss).

**Comment by cboettig** [comment]
Running the external monitor at a lower resolution seems to avoid the issue (2560x1440 instead of 3840x2160), but seems like a pity.  Perhaps lowering the monitor frequency instead would also help.  A bit surprised that this i7 chip doesn't handle the single 4k over display port well (even with the laptop monitor switched off).

**Comment by bezerker** [comment]
I experience this issue with the internal display on the QHD model.

running kernel 4.1.1

**Comment by soren121** [comment]
@bezerker Try adding `i915.enable_ips=0` to your kernel-command-line.

**Comment by bezerker** [comment]
Currently running that option with no luck.

**Comment by growing** [comment]
Upgrading the kernel to 4.1.6-040106-generic fixed this for me. 

More info here; http://hgdev.co/installing-ubuntu-15-04-on-the-xps-13-9343-2015-a-complete-guide/

**Comment by bezerker** [comment]
Hrm. I still get this on the internal display (not external)

4.1.6 and I get the following in dmesg

https://gist.github.com/bezerker/a8a84bf20ebf46ccaca4

I am suspecting bad hardware though.

**Comment by growing** [comment]
I only had the problem with an external monitor (Dell 23inch HiDPI), and the error message was;

drm:intel_set_cpu_fifo_underrun_reporting [i915]

Looks like yours is a different error :(

**Comment by cboettig** [comment]
I only experience this with the external display, and only when it is at 4K resolution.  Just upgraded to 4.1.6 kernel, but the same issue persists.  `dmseg` shows 

``` bash
[   82.786950] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun
```

not sure if that's the same issue @growing experienced.

**Comment by growing** [comment]
hey @cboettig that is the same issue I had. sorry that upgrading didn't fix it for you. 

if it helps these are the specs of my machine;
- bios A05
- ubuntu gnome 15.04 (http://ubuntugnome.org/ubuntu-gnome-15-04-is-released/)
- dell 24 inch 4k monitor (http://accessories.us.dell.com/sna/productdetail.aspx?c=us&l=en&cs=19&sku=860-BBCD)
- kernel linux-image-4.1.6-040106

**Comment by cboettig** [comment]
Just upgraded to 4.2 kernel as suggested in https://github.com/mpalourdio/xps13/issues/50#issuecomment-138819653 (though that thread appears to be for the built-in display, which has always been fine for me).  So far this seems to have fixed the problem I had on the 4K 27" Dell display (P2715Q) at full resolution (3840 x 2160, 60 Hz) over display port.  

However, for some reason I still cannot connect to the U3415W at full resolution (3440x1440), even though that's fewer pixels.  Whereas the 27" would just blank out occasionally with the `dmseg` about `drm:intel_cpu_fifo_underrun_irq_handler` mentioned above, the 34" never displays anything at full resolution; with the monitor going blank and then going to sleep even though it is detected correctly in display menu.  Running the 34" at lower resolution works just fine.  

Mostly I find running the external monitor at a lower resolution is a nuisance just because I need different unity-tweak zoom settings when I switch back and forth from laptop on-the-go to docked at the monitor (or have to run at reduced resolution on the go for no other reason).

**Comment by cboettig** [comment]
Just a note that I have recently still been seeing some unexpected behavior at the 4K resolution now, such as occasionally unresponsive mouse clicks; after which `dmseg` seems to show a lot of: 

```
[drm:gen8_irq_handler [i915]] *ERROR* The master control interrupt lied (SDE)!
```

so some i915 issues seem to persist.

**Comment by rpbaptist** [comment]
I have worked on a 2560x1440 display succesfully. Recently working with a 3440x1440 display and got this exact issue. At some points the screen will black out.

Cycling through display options with super+P returns it, but it's a nuisance.

**Comment by rpbaptist** [comment]
Not sure if this is the same problem, but I found it's a combination with an external hi-res display, chrome/chromium and certain websites.

Opening the AWS console for example will result in a complete black screen. Using shortcut ctrl+w to close the tab restores the screen. Opening the same page in Firefox solves it. I am slowly switching over to Firefox now, it seems.

Digging into it, this seems to be a problem with Chromium and Intel graphics. There is nothing in any of the log files. Not on system or Chromium. Changing all sorts of hardware rendering options in Chromium made no difference to me.

**Comment by zh4ngx** [comment]
+1
I am also having this issue on a 2020 Dell XPS 13 Developer Edition. This laptop is sold with a built-in 4k panel. I left most things untouched out of the box. Playing 4k YouTube video seems to trigger this every 10 seconds, on top of maxing out all 8 threads, which seems kind of crazy. Am I missing something?

**Comment by antonmry** [comment]
Just in case, I had this issue and it was solved when I changed the HDMI cable. It may don't solve the problem for everybody but it's something easy to try.

**Comment by zh4ngx** [comment]
I am using an included Thunderbolt 3 cable (supposedly rated for 40Gbps) to connect to a BenQ PD3220U (rated for 85W PD). The problem seems to me worse when I stress the CPU, but it is happening even now as I am typing this. Will try another TB3 cable, but any way I can check the connectivity quality in Ubuntu? Both for the PD and the DP connection? I couldn't get much from boltctl

<pre>boltctl 
 <font color="#4E9A06">●</font> BenQ PD3220U
   ├─ type:          peripheral
   ├─ name:          PD3220U
   ├─ vendor:        BenQ
   ├─ uuid:          0072e28c-4174-c401-ffff-ffffffffffff
   ├─ status:        authorized
   │  ├─ domain:     domain0
   │  └─ authflags:  none
   ├─ authorized:    Wed 29 Jul 2020 07:45:13 PM UTC
   ├─ connected:     Wed 29 Jul 2020 07:45:13 PM UTC
   └─ stored:        no
</pre>

**Comment by zh4ngx** [comment]
Update - solved on my end. @antonmry your suggestion reminded me to check the power chain, and I realized my monitor was not plugged into the correct strip :smile: . This particular machine still can't do 4k60fps, but I believe that is an actual CPU bottleneck or just not a great codec implementation on Ubuntu.
